--script do banco

CREATE TABLE PRODUCT (
    CODE INTEGER NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(30) NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE AUDITING (
    IDENTIFIER INTEGER NOT NULL,
    REGISTERFROM VARCHAR(30) NOT NULL,
    REGISTERCODE VARCHAR(30) NOT NULL,
    OPERATION VARCHAR(30) NOT NULL,
    DATETIME TIMESTAMP NOT NULL,
    PRIMARY KEY (IDENTIFIER)
);